// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BusquedaxCiudadxFechaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void busquedaxCiudadxFecha() {
    driver.get("http://g2-frontend-destiautos.s3-website.us-east-2.amazonaws.com/home");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.id("cities")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cities"));
      dropdown.findElement(By.xpath("//option[. = 'Medellin']")).click();
    }
    driver.findElement(By.cssSelector(".ant-picker-input-active > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > .ant-picker-cell-start > .ant-picker-cell-inner")).click();
    driver.findElement(By.cssSelector(".ant-picker-time-panel-cell-selected:nth-child(23) > .ant-picker-time-panel-cell-inner")).click();
    assertThat(driver.findElement(By.cssSelector(".ant-btn > span")).getText(), is("OK"));
    driver.findElement(By.cssSelector(".ant-picker-cell-range-hover-end > .ant-picker-cell-inner")).click();
    driver.findElement(By.cssSelector(".ant-picker-time-panel-cell-selected:nth-child(23) > .ant-picker-time-panel-cell-inner")).click();
    assertThat(driver.findElement(By.cssSelector(".ant-btn")).getText(), is("OK"));
    assertThat(driver.findElement(By.cssSelector(".button--5")).getText(), is("Search"));
    driver.findElement(By.cssSelector(".card:nth-child(3) .button--4")).click();
  }
}
