// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdministradorCreaProductoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void administradorCreaProducto() {
    driver.get("http://g2-frontend-destiautos.s3-website.us-east-2.amazonaws.com/home");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".inline-block:nth-child(2) > .button--4")).click();
    driver.findElement(By.id("emailLogin")).click();
    driver.findElement(By.id("emailLogin")).sendKeys("admin@gmail.com");
    driver.findElement(By.id("passwordLogin")).sendKeys("administradorBD");
    driver.findElement(By.id("passwordLogin")).click();
    driver.findElement(By.cssSelector(".button2")).click();
    js.executeScript("window.scrollTo(0,232.88888549804688)");
    {
      WebElement element = driver.findElement(By.cssSelector(".header__manager"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".header__manager"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".header__manager"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".header")).click();
    driver.findElement(By.cssSelector(".header")).click();
    driver.findElement(By.cssSelector(".header__manager > h4")).click();
    driver.findElement(By.name("productName")).click();
    driver.findElement(By.name("productName")).sendKeys("Audi");
    driver.findElement(By.name("brand")).click();
    driver.findElement(By.name("brand")).sendKeys("Audi");
    driver.findElement(By.name("model")).click();
    driver.findElement(By.name("model")).sendKeys("2020");
    driver.findElement(By.id("category_id")).click();
    {
      WebElement dropdown = driver.findElement(By.id("category_id"));
      dropdown.findElement(By.xpath("//option[. = 'Saloon']")).click();
    }
    driver.findElement(By.name("priceDay")).click();
    driver.findElement(By.name("priceDay")).sendKeys("2.9");
    driver.findElement(By.id("availability")).click();
    {
      WebElement dropdown = driver.findElement(By.id("availability"));
      dropdown.findElement(By.xpath("//option[. = 'Low']")).click();
    }
    driver.findElement(By.name("carLicensePlate")).click();
    driver.findElement(By.name("carLicensePlate")).sendKeys("ass34");
    driver.findElement(By.id("city_id")).click();
    {
      WebElement dropdown = driver.findElement(By.id("city_id"));
      dropdown.findElement(By.xpath("//option[. = 'Bogota']")).click();
    }
    driver.findElement(By.cssSelector(".product-form__textarea")).click();
    driver.findElement(By.cssSelector(".product-form__textarea")).sendKeys("dasdaf");
    driver.findElement(By.cssSelector(".product-form__features-block--first-row")).click();
    driver.findElement(By.id("featuresProducts")).click();
    {
      WebElement dropdown = driver.findElement(By.id("featuresProducts"));
      dropdown.findElement(By.xpath("//option[. = '4 Doors']")).click();
    }
    driver.findElement(By.cssSelector(".product-form__features-block > .button__plus")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".product-form__features-block > .button__plus"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("featuresProducts")).click();
    {
      WebElement dropdown = driver.findElement(By.id("featuresProducts"));
      dropdown.findElement(By.xpath("//option[. = '2 Airbags']")).click();
    }
    driver.findElement(By.cssSelector(".product-form__features-block > .button__plus")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".product-form__features-block > .button__plus"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("title")).click();
    {
      WebElement dropdown = driver.findElement(By.name("title"));
      dropdown.findElement(By.xpath("//option[. = 'Carrusel\'s Main Image']")).click();
    }
    driver.findElement(By.name("image")).click();
    driver.findElement(By.cssSelector(".product-form")).click();
    driver.findElement(By.cssSelector(".product-form")).click();
  }
}
