// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistroUsuarioAnnimoClaveprotegidaLoginLogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registroUsuarioAnnimoClaveprotegidaLoginLogout() {
    driver.get("http://g2-frontend-destiautos.s3-website.us-east-2.amazonaws.com/home");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".inline-block:nth-child(1) > .button--4")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Jorge");
    driver.findElement(By.id("lastname")).click();
    driver.findElement(By.id("lastname")).sendKeys("Guzman");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("guzman@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("021019993.");
    driver.findElement(By.id("confirmPassword")).click();
    driver.findElement(By.id("confirmPassword")).sendKeys("021019993.");
    driver.findElement(By.cssSelector(".button2")).click();
    assertThat(driver.switchTo().alert().getText(), is("Signin Successfull"));
    driver.findElement(By.cssSelector(".inline-block:nth-child(2) > .button--4")).click();
    driver.findElement(By.id("emailLogin")).click();
    driver.findElement(By.id("emailLogin")).sendKeys("guzman@gmail.com");
    driver.findElement(By.id("passwordLogin")).sendKeys("021019993.");
    driver.findElement(By.id("passwordLogin")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".header__right__button")).click();
  }
}
