// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ReservaUserNoLogueadoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void reservaUserNoLogueado() {
    driver.get("http://g2-frontend-destiautos.s3-website.us-east-2.amazonaws.com/home");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".card:nth-child(3) .button--4")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".headerBlock__left > h1")).click();
    driver.findElement(By.cssSelector(".react-calendar__month-view:nth-child(2) .react-calendar__tile:nth-child(30)")).click();
    driver.findElement(By.cssSelector(".react-calendar__tile--hover:nth-child(4) > abbr")).click();
    driver.findElement(By.cssSelector(".buttonReserve > button")).click();
    js.executeScript("window.scrollTo(0,490.3999938964844)");
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("! In order to set a reservation you must log in"));
    driver.findElement(By.cssSelector(".form")).click();
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.cssSelector(".inline-block:nth-child(1) > .button--4")).click();
  }
}
