// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FechasDisponiblesenDetallesdelProductoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fechasDisponiblesenDetallesdelProducto() {
    driver.get("http://g2-frontend-destiautos.s3-website.us-east-2.amazonaws.com/home");
    driver.manage().window().setSize(new Dimension(1552, 832));
    assertThat(driver.findElement(By.cssSelector(".card:nth-child(1) .button--4")).getText(), is("DETAILS"));
    driver.findElement(By.cssSelector(".booking")).click();
    driver.findElement(By.cssSelector(".react-calendar--doubleView .react-calendar__navigation__next-button")).click();
    driver.findElement(By.cssSelector(".react-calendar--doubleView .react-calendar__navigation__next-button")).click();
  }
}
